### ISSUE TITLE
Request:  Add tooltips to placed containers like chests

### ISSUE THREAD

**Issue by NBKRedSpy** [computerfan/CstiDetailedCardProgress#2]
Would it be possible to add the tool tips to the containers that are placed in the location row?  For example chests and "placed" baskets?

**Comment by computerfan** [comment]
I intentionally disabled weight tooltips on placed containers because they cannot be picked up. You can enable it by appending CardTypes.Location to isShowWeightType following CardTypes.Item.
https://github.com/computerfan/CstiDetailedCardProgress/blob/d75d5e5cf47938ec44124e88da5a761b9c625048/Plugin.cs#L65
I think I'll enable it later since placed items take up room weight.

**Comment by NBKRedSpy** [comment]
Can't wait to try it out.  Thanks!
